//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureTableStorageScaffolder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureTableStorageScaffolder.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new data context....
        /// </summary>
        public static string WebFormsCodeGeneratorViewModel_AddNewDbContext {
            get {
                return ResourceManager.GetString("WebFormsCodeGeneratorViewModel_AddNewDbContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates pages for listing, creating, updating, viewing and deleting using MVC WebAPI 2.0 and KendoUI controls..
        /// </summary>
        public static string WebFormsScaffolder_Description {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razor Pages using Microsoft Azure Table Storage.
        /// </summary>
        public static string WebFormsScaffolder_Name {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the model type. If the project is not built, try building the project..
        /// </summary>
        public static string WebFormsScaffolder_ProjectNotBuilt {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_ProjectNotBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a valid DbContext class..
        /// </summary>
        public static string WebFormsScaffolder_SelectDbContextType {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_SelectDbContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a valid model class..
        /// </summary>
        public static string WebFormsScaffolder_SelectModelType {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_SelectModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowUIAndValidate needs to be called prior to this method..
        /// </summary>
        public static string WebFormsScaffolder_ShowUIAndValidateNotCalled {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_ShowUIAndValidateNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action name cannot be null or empty..
        /// </summary>
        public static string WebFormsViewScaffolder_EmptyActionName {
            get {
                return ResourceManager.GetString("WebFormsViewScaffolder_EmptyActionName", resourceCulture);
            }
        }
    }
}
