//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSample.Views.WeightUnit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCSample.Views.WeightUnit.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} entity..
        /// </summary>
        public static string WeightUnit_Create_Form_Header_Format {
            get {
                return ResourceManager.GetString("WeightUnit_Create_Form_Header_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string WeightUnit_Create_Form_Options {
            get {
                return ResourceManager.GetString("WeightUnit_Create_Form_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string WeightUnit_Create_Save {
            get {
                return ResourceManager.GetString("WeightUnit_Create_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        public static string WeightUnit_Create_Title_Format {
            get {
                return ResourceManager.GetString("WeightUnit_Create_Title_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string WeightUnit_Delete_Delete {
            get {
                return ResourceManager.GetString("WeightUnit_Delete_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} entity..
        /// </summary>
        public static string WeightUnit_Delete_Form_Header_Format {
            get {
                return ResourceManager.GetString("WeightUnit_Delete_Form_Header_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string WeightUnit_Delete_Form_Options {
            get {
                return ResourceManager.GetString("WeightUnit_Delete_Form_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string WeightUnit_Delete_Title_Format {
            get {
                return ResourceManager.GetString("WeightUnit_Delete_Title_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string WeightUnit_Details_Delete {
            get {
                return ResourceManager.GetString("WeightUnit_Details_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string WeightUnit_Details_Edit {
            get {
                return ResourceManager.GetString("WeightUnit_Details_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0} entity..
        /// </summary>
        public static string WeightUnit_Details_Form_Header_Format {
            get {
                return ResourceManager.GetString("WeightUnit_Details_Form_Header_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string WeightUnit_Details_Form_Options {
            get {
                return ResourceManager.GetString("WeightUnit_Details_Form_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0}.
        /// </summary>
        public static string WeightUnit_Details_Title_Format {
            get {
                return ResourceManager.GetString("WeightUnit_Details_Title_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} entity..
        /// </summary>
        public static string WeightUnit_Edit_Form_Header_Format {
            get {
                return ResourceManager.GetString("WeightUnit_Edit_Form_Header_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string WeightUnit_Edit_Form_Options {
            get {
                return ResourceManager.GetString("WeightUnit_Edit_Form_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string WeightUnit_Edit_Save {
            get {
                return ResourceManager.GetString("WeightUnit_Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        public static string WeightUnit_Edit_Title_Format {
            get {
                return ResourceManager.GetString("WeightUnit_Edit_Title_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string WeightUnit_Index_Create {
            get {
                return ResourceManager.GetString("WeightUnit_Index_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string WeightUnit_Index_Create_New {
            get {
                return ResourceManager.GetString("WeightUnit_Index_Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string WeightUnit_Index_Delete {
            get {
                return ResourceManager.GetString("WeightUnit_Index_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string WeightUnit_Index_Edit {
            get {
                return ResourceManager.GetString("WeightUnit_Index_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} entity..
        /// </summary>
        public static string WeightUnit_Index_Form_Header_Format {
            get {
                return ResourceManager.GetString("WeightUnit_Index_Form_Header_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        public static string WeightUnit_Index_Title_Format {
            get {
                return ResourceManager.GetString("WeightUnit_Index_Title_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string WeightUnit_Index_View {
            get {
                return ResourceManager.GetString("WeightUnit_Index_View", resourceCulture);
            }
        }
    }
}
